---

language: ruby
rvm:
  - 2.6.3

cache:
  bundler: true

install:
  - psql -c 'create database qna_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:setup
  - cp .env.example .env
  - bundle install --jobs 3 --retry 3

script:
  - make lint
  - make test
 Gemfile
