---

language: ruby
rvm:
  - 2.6.3

cache:
  bundler: true

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

services:
  - postgresql
  - redis-server

install:
  - cp config/database.travis.yml config/database.yml
  - cp .env.example .env
  - bundle install --jobs 3 --retry 3

script:
  - bundle exec rake db:setup
  - make lint
  - make test
