---

language: ruby
rvm:
  - 2.6.3

cache:
  bundler: true

addons:
  postgresql: "10"

services:
  - postgresql

install:
  - cp config/database.travis.yml config/database.yml
  - cp .env.example .env
  - bundle install --jobs 3 --retry 3

script:
  - make lint
  - make test
