---

language: ruby
rvm:
  - 2.6.3

cache:
  bundler: true

addons:
  postgresql: "10"

services:
  - postgresql

install:
  - bundle install --jobs 3 --retry 3
  - psql -c 'create database qna_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:setup
  - cp .env.example .env

script:
  - make lint
  - make test
